<?php
/**导入模板配置
 * Created by PhpStorm.
 * User: LVISON
 * Date: 2016/9/27
 * Time: 11:15
 */

return  array(
    //评标线路导入模板
    'tender_route' => array(
        array(
            'tbname' => '',
            'width' => 120,
            'fieldname' => 'from_location',
            'text' => '起始站点',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 120,
            'fieldname' => 'to_location',
            'text' => '到达站点',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 120,
            'fieldname' => 'price',
            'text' => '最高限额(元/吨)',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'over_rate',
            'text' => '超额标准(%)-请填整数',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'months',
            'text' => '月份-请填数字',
            'nameedit' => '',
            'fieldtype' => 'tinyint',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 3,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'ship_method',
            'text' => '运输方式',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'carriage_type',
            'text' => '箱型',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'density',
            'text' => '重泡货',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        )
    ),

    //挂靠车导入
    'affiliated' => array(
        array(
            'tbname' => '',
            'width' => 120,
            'fieldname' => 'carnum',
            'text' => '车牌号',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 120,
            'fieldname' => 'car_length',
            'text' => '车长',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 120,
            'fieldname' => 'rated_load',
            'text' => '额定载重(吨)',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'carriage_type',
            'text' => '厢型',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'driver_name',
            'text' => '司机姓名',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'driver_phone',
            'text' => '司机电话',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        ),
        array(
            'tbname' => '',
            'width' => 200,
            'fieldname' => 'id_card',
            'text' => '身份证号',
            'nameedit' => '',
            'fieldtype' => 'varchar',
            'fieldlen' => 20,
            'datatype' => 'varchar',
            'validate' => array('maxlength' => 20),
            'defaultval' => '',
            'xnum' => 255,
            'type' => 1, //1自有，2自定义
            'isrequired' => 1,
            'isshow' => 1,
            'isdict'    =>  array(),
        )
    ),
);